apiVersion: v1
kind: Service
metadata:
  name: fluentsearch-admission-service
  namespace: fluentsearch-admission
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: fluentsearch-admission
  ports:
    - port: 3000
