apiVersion: v1
kind: Service
metadata:
  name: fluentsearch-spotlight-service
  namespace: fluentsearch-spotlight
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: fluentsearch-spotlight
  ports:
    - port: 3000
