apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentsearch-bff-config
  namespace: fluentsearch-bff
data:
  NODE_ENV: "production"
  TZ: Asia/Bangkok
  ORIGIN: "http(|s)://api.fluentsearch.ml|localhost|fluentsearch.ml"
  DATABASE_CONNECTION: "mongodb://fluentsearch-mongodb-mongodb-sharded.fluentsearch-mongo-db.svc.cluster.local/fluentsearch"
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: Fluent$earch@MongoDB
  DATABASE_AUTH_SOURCE: admin
  JWT_SECRET_KEY: jwt1secret
  JWT_EXPIRES: "86400000"
  SESSION_SECRET: session1secret
  SESSION_EXPIRES: "86400000"
  PORT: "5000"
  HOSTNAME: "api.fluentsearch.ml"
  MAIN_HOSTNAME: "fluentsearch.ml"
  STORAGE_ENDPOINT: storage.fluentsearch.ml
  MINIO_ACCESS_KEY: "root"
  MINIO_SECRET_KEY: "Fluent$earch@Minio"
  MINIO_SERVER_ENDPOINT: "minio.minio-tenant-1.svc.cluster.local"
  MINIO_SERVER_PORT: "443"
  MINIO_SERVER_SSL: "true"
