apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentsearch-bff-config
  namespace: fluentsearch-bff
data:
  NODE_ENV: "development"
  TZ: "Asia/Bangkok"
  ORIGIN: "http(|s)://fluentsearch.ml"
  DATABASE_CONNECTION: "mongodb://fluentsearch-mongodb.fluentsearch-mongo-db.svc.cluster.local/fluentsearch-bff"
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "Fluent$earch@MongoDB"
  DATABASE_AUTH_SOURCE: "admin"
  PORT: "5000"
