apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentsearch-bff-config
  namespace: fluentsearch-bff
data:
  NODE_ENV: "production"
  TZ: Asia/Bangkok
  ORIGIN: http(|s):\/\/localhost:5000
  DATABASE_CONNECTION: "mongodb://fluentsearch-mongodb-mongodb-sharded.fluentsearch-mongo-db.svc.cluster.local/fluentsearch-bff"
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: FluentSearch@BFF.MongoDB
  DATABASE_AUTH_SOURCE: admin
  JWT_SECRET_KEY: jwt1secret
  JWT_EXPIRES: 300000
  SESSION_SECRET: session1secret
  SESSION_EXPIRES: 86400000
  PORT: 5000
