apiVersion: v1
kind: Service
metadata:
  name: fluentsearch-bff-service
  namespace: fluentsearch-bff
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: fluentsearch-bff
  ports:
    - port: 5000
