apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentsearch-api-federation-config
  namespace: fluentsearch-api-federation
data:
  NODE_ENV: "production"
  TZ: Asia/Bangkok
  ORIGIN: "http(|s)://federation.fluentsearch.ml|localhost|fluentsearch.ml"
  BFF_ENDPOINT: http://fluentsearch-bff-service.fluentsearch-bff.svc.cluster.local:5000/graphql
  ADMISSION_ENDPOINT: http://fluentsearch-admission-service.fluentsearch-admission.svc.cluster.local:3000/graphql
  SPOTLIGHT_ENDPOINT: http://fluentsearch-spotlight-service.fluentsearch-spotlight.svc.cluster.local:3000/graphql
  STORAGE_ENDOINT: http://fluentsearch-storage-service.fluentsearch-storage.svc.cluster.local:3000/graphql
