apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentsearch-ml
  namespace: fluentsearch-ml
  labels:
    app: fluentsearch-ml
spec:
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
  nodeSelector:
    doks.digitalocean.com/node-pool: ml-pool
  replicas: 4
  selector:
    matchLabels:
      app: fluentsearch-ml
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: fluentsearch-ml
    spec:
      containers:
        - name: fluentsearch-api-federation
          image: jolibrain/deepdetect_cpu
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
