apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentsearch-bff
  name: fluentsearch-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluentsearch-bff
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: fluentsearch-bff
    spec:
      containers:
        - env:
            - name: DATABASE_AUTH_SOURCE
              value: admin
            - name: DATABASE_CONNECTION
              value: mongodb://fluentsearch-bff-mongos/fluentsearch-bff
            - name: DATABASE_PASSWORD
              value: FluentSearch@BFF.MongoDB
            - name: DATABASE_USERAME
              value: root
            - name: NODE_ENV
              value: development
            - name: ORIGIN
              value: http(|s):\/\/localhost:5000
            - name: PORT
              value: "5000"
            - name: TZ
              value: Asia/Bangkok
          image: fluentsearch-bff
          name: fluentsearch-bff
          ports:
            - containerPort: 5000
            - containerPort: 9229
          resources: {}
          volumeMounts:
            - mountPath: /src
              name: fluentsearch-bff-claim0
            - mountPath: /schema.gql
              name: fluentsearch-bff-claim1
      restartPolicy: Always
      volumes:
        - name: fluentsearch-bff-claim0
          persistentVolumeClaim:
            claimName: fluentsearch-bff-claim0
        - name: fluentsearch-bff-claim1
          persistentVolumeClaim:
            claimName: fluentsearch-bff-claim1
status: {}
