apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentsearch-bff-mongos
  name: fluentsearch-bff-mongos
spec:
  containers:
    - env:
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: fluentsearch-bff-mongos
        - name: MONGODB_CFG_PRIMARY_HOST
          value: fluentsearch-bff-cfg
        - name: MONGODB_CFG_REPLICA_SET_NAME
          value: fluentsearch-bff-cfg
        - name: MONGODB_REPLICA_SET_KEY
          value: fluentsearchbff
        - name: MONGODB_ROOT_PASSWORD
          value: FluentSearch@BFF.MongoDB
        - name: MONGODB_SHARDING_MODE
          value: mongos
        - name: TZ
          value: Asia/Bangkok
      image: bitnami/mongodb-sharded:4.4
      name: fluentsearch-bff-mongos
      ports:
        - containerPort: 27017
      resources: {}
  restartPolicy: OnFailure
status: {}
